/**
 * One-shot script to create the MindDuel Mock USDC mint on devnet.
 *
 * Usage:
 *   1. Place your funded devnet keypair JSON at backend/.keys/payer.json
 *      (or set PAYER_KEYPAIR_PATH env). Min ≈0.05 SOL needed.
 *   2. npm --workspace @mind-duel/backend run setup:usdc
 *
 * Outputs:
 *   - Mint address (public — share with frontend via NEXT_PUBLIC_MOCK_USDC_MINT)
 *   - Mint authority secret key (private — paste into backend env as
 *     MINT_AUTHORITY_SECRET as JSON array of u8)
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { Connection, Keypair, clusterApiUrl } from '@solana/web3.js'
import { createMint } from '@solana/spl-token'

const RPC_URL    = process.env.RPC_URL ?? clusterApiUrl('devnet')
const DECIMALS   = 6
const KEYS_DIR   = resolve(process.cwd(), '.keys')
const PAYER_PATH = process.env.PAYER_KEYPAIR_PATH ?? resolve(KEYS_DIR, 'payer.json')
const AUTH_PATH  = resolve(KEYS_DIR, 'mint-authority.json')
const OUT_PATH   = resolve(process.cwd(), '.env.mock-usdc')

function loadKeypair(path: string): Keypair {
  const raw = readFileSync(path, 'utf8')
  return Keypair.fromSecretKey(Uint8Array.from(JSON.parse(raw)))
}

async function main() {
  if (!existsSync(PAYER_PATH)) {
    throw new Error(`Payer keypair not found at ${PAYER_PATH}. Place a funded devnet keypair JSON there.`)
  }

  const payer = loadKeypair(PAYER_PATH)
  console.log('Payer:', payer.publicKey.toBase58())

  const connection = new Connection(RPC_URL, 'confirmed')
  const lamports   = await connection.getBalance(payer.publicKey)
  console.log('Payer balance:', lamports / 1e9, 'SOL')
  if (lamports < 0.05 * 1e9) {
    console.warn('WARNING: payer has <0.05 SOL — may fail to create mint.')
  }

  if (!existsSync(KEYS_DIR)) mkdirSync(KEYS_DIR, { recursive: true })

  let mintAuthority: Keypair
  if (existsSync(AUTH_PATH)) {
    mintAuthority = loadKeypair(AUTH_PATH)
    console.log('Reusing mint authority:', mintAuthority.publicKey.toBase58())
  } else {
    mintAuthority = Keypair.generate()
    writeFileSync(AUTH_PATH, JSON.stringify(Array.from(mintAuthority.secretKey)))
    console.log('Generated new mint authority:', mintAuthority.publicKey.toBase58())
    console.log('  → secret saved to', AUTH_PATH)
  }

  console.log('Creating mint...')
  const mint = await createMint(
    connection,
    payer,
    mintAuthority.publicKey,
    null,
    DECIMALS,
  )
  console.log('✓ Mock USDC mint created:', mint.toBase58())

  const envBody = [
    `# Generated by setup-mock-usdc.ts on ${new Date().toISOString()}`,
    `MOCK_USDC_MINT=${mint.toBase58()}`,
    `MINT_AUTHORITY_SECRET=${JSON.stringify(Array.from(mintAuthority.secretKey))}`,
    `# Frontend (.env.local):`,
    `# NEXT_PUBLIC_MOCK_USDC_MINT=${mint.toBase58()}`,
    '',
  ].join('\n')

  if (!existsSync(dirname(OUT_PATH))) mkdirSync(dirname(OUT_PATH), { recursive: true })
  writeFileSync(OUT_PATH, envBody)
  console.log('✓ Wrote env values to', OUT_PATH)
  console.log()
  console.log('Next steps:')
  console.log('  1. Append contents of .env.mock-usdc to backend/.env')
  console.log('  2. Add NEXT_PUBLIC_MOCK_USDC_MINT to frontend/.env.local')
}

main().catch(err => {
  console.error('Setup failed:', err)
  process.exit(1)
})
