// Shared design tokens — import from here, never re-declare per file
export const BLUE        = '#0071E3'
export const BLUE_LIGHT  = '#E5F0FD'
export const INK         = '#1D1D1F'
export const MUTED       = '#6E6E73'
export const FAINT       = '#AEAEB2'
export const BG          = '#F5F5F7'
export const SURFACE     = '#ffffff'
export const GREEN       = '#34C759'
export const GREEN_DARK  = '#0A7A2D'
export const GREEN_LIGHT = '#E8F7EE'
export const RED         = '#FF3B30'
export const RED_DARK    = '#A81C13'
export const RED_LIGHT   = '#FDECEB'
export const ORANGE      = '#FF9500'
